version: "3.2"
services:
  easylog_backend:
    container_name: easylog_backend_server
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      SYSTEM_PORT: ${SYSTEM_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
    volumes:
      - "../:/var/www/app"
      - "/var/www/app/node_modules"
    networks:
      - easylog_backend-net
    depends_on:
      - easylog_db
    ports:
      - ${SYSTEM_PORT}:${SYSTEM_PORT}
    command: ${COMMAND_START}

networks:
  easylog_backend-net:
    driver: bridge
